In [67]:
def squares(values):
    result = []
    for v in values:
        result.append(v * v)
    return result

In [68]:
to_square = range(100000)

In [69]:
%timeit squares(to_square)

63.8 ms ± 2.67 ms per loop (mean ± std. dev. of 7 runs, 10 loops each)


In [1]:
import numpy as np

In [71]:
array_to_square = np.arange(0, 100000)

In [72]:
%timeit array_to_square ** 2

319 µs ± 36.4 µs per loop (mean ± std. dev. of 7 runs, 1000 loops each)


# Creating NumPy Arrays

## Methods:
#1-Simple array func:
#2-Simple array func with repeated sequence
#3-arange func --> 2 methods
#4-linspace func:
#5-zeros func:
#6-ones func:

### syntex for creating a Numpy array:
array_name=np.array([values])

In [2]:
import numpy as np #importing the class of Numpy

In [74]:
a1=np.array([1,2,3,4,5,6,7])#creating a simple array 

In [4]:
print(a1)

[1 2 3 4 5 6 7]


In [5]:
type(a1)

numpy.ndarray

In [6]:
a1.dtype #give the datatype of the array

dtype('int32')

In [7]:
np.size(a1)#how many elements are there in array

7

#### NumPy arrays must have all of their elements of the same type. If you specify different types in the list, NumPy will try to coerce all the items to the same type.

In [79]:
a2=np.array([1,2,3,4,5.5])
print(a2)

[1.  2.  3.  4.  5.5]


In [9]:
type(a2)

numpy.ndarray

In [10]:
a2.dtype

dtype('float64')

#### An array of a specific size can be created in multiple ways. The following code uses a single item Python list to initialize an array of 10 items

### shorthand to repeat a sequence n times
syntex: array_name=np.array([value]*multipiler)

In [11]:
a3=np.array([0]*10)
print(a3)

[0 0 0 0 0 0 0 0 0 0]


In [12]:
a31=np.array([5.5]*20)
print(a31)

[5.5 5.5 5.5 5.5 5.5 5.5 5.5 5.5 5.5 5.5 5.5 5.5 5.5 5.5 5.5 5.5 5.5 5.5
 5.5 5.5]


In [13]:
a32=np.array([18]*5)
print(a32)

[18 18 18 18 18]


In [15]:
a33=np.array([4.5,6.7,9.7]*3)
print(a33)

[4.5 6.7 9.7 4.5 6.7 9.7 4.5 6.7 9.7]


### convert a python range to numpy array {method-1}

In [17]:
a4=np.arange(10)
print(a4)

[0 1 2 3 4 5 6 7 8 9]


### {mehtod-2}

In [19]:
a41=np.array(range(10))
print(a41)

[0 1 2 3 4 5 6 7 8 9]


In [26]:
#range()- it is similar to the basic python
#range(start,end,step_size)

#method-1
a42=np.arange(0,10,2)#array of even num from 0 to 10
print(a42)
#method-2
a43=np.array(range(1,10,2))#array of odd num from 0 to 10
print(a43)

[0 2 4 6 8]
[1 3 5 7 9]


### create a numpy array of n 0.0's

In [20]:
a5=np.zeros(4)

In [21]:
a5

array([0., 0., 0., 0.])

In [22]:
a5.dtype #bydefault func zeros() will create array of floating number

dtype('float64')

In [23]:
a51=np.zeros(6,dtype=int)

In [24]:
a51

array([0, 0, 0, 0, 0, 0])

### create a numpy array of n 1's

In [7]:
a52=np.ones(4)

In [8]:
a52

array([1., 1., 1., 1.])

In [10]:
a53=np.ones(3,dtype=int)
a53

array([1, 1, 1])

### Creating a numpy array using linspace()

#### The np.linspace() function is similar to np.arange(), but generates an array of a specific number of items between the specified start and stop values

In [34]:
# evenly spaced nums between two intervals
a6=np.linspace(1,2,9)
print(a6)

[1.    1.125 1.25  1.375 1.5   1.625 1.75  1.875 2.   ]


In [32]:
a6.dtype

dtype('float64')

In [12]:
a61=np.linspace(1,2)#by default linspace will create an array of 50 values
a61

array([1.        , 1.02040816, 1.04081633, 1.06122449, 1.08163265,
       1.10204082, 1.12244898, 1.14285714, 1.16326531, 1.18367347,
       1.20408163, 1.2244898 , 1.24489796, 1.26530612, 1.28571429,
       1.30612245, 1.32653061, 1.34693878, 1.36734694, 1.3877551 ,
       1.40816327, 1.42857143, 1.44897959, 1.46938776, 1.48979592,
       1.51020408, 1.53061224, 1.55102041, 1.57142857, 1.59183673,
       1.6122449 , 1.63265306, 1.65306122, 1.67346939, 1.69387755,
       1.71428571, 1.73469388, 1.75510204, 1.7755102 , 1.79591837,
       1.81632653, 1.83673469, 1.85714286, 1.87755102, 1.89795918,
       1.91836735, 1.93877551, 1.95918367, 1.97959184, 2.        ])

# Performing basic array operations

In [38]:
a1

array([1, 2, 3, 4, 5, 6, 7])

In [35]:
a1*2

array([ 2,  4,  6,  8, 10, 12, 14])

In [36]:
a1+2

array([3, 4, 5, 6, 7, 8, 9])

In [37]:
a1-2

array([-1,  0,  1,  2,  3,  4,  5])

In [39]:
a1/2

array([0.5, 1. , 1.5, 2. , 2.5, 3. , 3.5])

In [40]:
a1%2

array([1, 0, 1, 0, 1, 0, 1], dtype=int32)

In [46]:
a7=np.linspace(4,5)
a7

array([4.        , 4.02040816, 4.04081633, 4.06122449, 4.08163265,
       4.10204082, 4.12244898, 4.14285714, 4.16326531, 4.18367347,
       4.20408163, 4.2244898 , 4.24489796, 4.26530612, 4.28571429,
       4.30612245, 4.32653061, 4.34693878, 4.36734694, 4.3877551 ,
       4.40816327, 4.42857143, 4.44897959, 4.46938776, 4.48979592,
       4.51020408, 4.53061224, 4.55102041, 4.57142857, 4.59183673,
       4.6122449 , 4.63265306, 4.65306122, 4.67346939, 4.69387755,
       4.71428571, 4.73469388, 4.75510204, 4.7755102 , 4.79591837,
       4.81632653, 4.83673469, 4.85714286, 4.87755102, 4.89795918,
       4.91836735, 4.93877551, 4.95918367, 4.97959184, 5.        ])

In [48]:
a8=np.linspace(7,8)
a8

array([7.        , 7.02040816, 7.04081633, 7.06122449, 7.08163265,
       7.10204082, 7.12244898, 7.14285714, 7.16326531, 7.18367347,
       7.20408163, 7.2244898 , 7.24489796, 7.26530612, 7.28571429,
       7.30612245, 7.32653061, 7.34693878, 7.36734694, 7.3877551 ,
       7.40816327, 7.42857143, 7.44897959, 7.46938776, 7.48979592,
       7.51020408, 7.53061224, 7.55102041, 7.57142857, 7.59183673,
       7.6122449 , 7.63265306, 7.65306122, 7.67346939, 7.69387755,
       7.71428571, 7.73469388, 7.75510204, 7.7755102 , 7.79591837,
       7.81632653, 7.83673469, 7.85714286, 7.87755102, 7.89795918,
       7.91836735, 7.93877551, 7.95918367, 7.97959184, 8.        ])

In [49]:
a7+a8

array([11.        , 11.04081633, 11.08163265, 11.12244898, 11.16326531,
       11.20408163, 11.24489796, 11.28571429, 11.32653061, 11.36734694,
       11.40816327, 11.44897959, 11.48979592, 11.53061224, 11.57142857,
       11.6122449 , 11.65306122, 11.69387755, 11.73469388, 11.7755102 ,
       11.81632653, 11.85714286, 11.89795918, 11.93877551, 11.97959184,
       12.02040816, 12.06122449, 12.10204082, 12.14285714, 12.18367347,
       12.2244898 , 12.26530612, 12.30612245, 12.34693878, 12.3877551 ,
       12.42857143, 12.46938776, 12.51020408, 12.55102041, 12.59183673,
       12.63265306, 12.67346939, 12.71428571, 12.75510204, 12.79591837,
       12.83673469, 12.87755102, 12.91836735, 12.95918367, 13.        ])

In [41]:
a1

array([1, 2, 3, 4, 5, 6, 7])

In [42]:
a4

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [43]:
a1+a4

ValueError: operands could not be broadcast together with shapes (7,) (10,) 

# Multi-Dimensional Array

#### NumPy arrays are n-dimensional, but for purposes of pandas, we will be most interested in one- and two-dimensional arrays.
#syntex for 2d array: array_name=np.array([[values],[values],[values],......,[values]])

In [46]:
md1=np.array([[1,2,3],[6,7,8]])
print(md1)
print("shape of array",np.shape(md1))# shape()--> The elements of the shape tuple give the lengths of the corresponding array dimensions.
print("dimensions of array",np.ndim(md1))# .ndim shows the dimensions of array

[[1 2 3]
 [6 7 8]]
shape of array (2, 3)
dimensions of array 2


In [18]:
md1a=np.array([[1,2]])
print(md1a)
np.shape(md1a)

[[1 2]]


(1, 2)

In [47]:
np.ndim(md1a)

2

In [66]:
#create a 2-dimensional array (3x2)
md2=np.array([[3,4],[1,2],[7,8]])
print(md2)
np.shape(md2)

[[3 4]
 [1 2]
 [7 8]]


(3, 2)

In [38]:
#creating a 3d array
m3d=np.array([[[1,2],[5,6],[9,1]]])
m3d

array([[[1, 2],
        [5, 6],
        [9, 1]]])

In [39]:
np.shape(m3d)

(1, 3, 2)

In [48]:
np.ndim(md3)

3

In [27]:
mda=np.linspace(3,5,9)
mdb=np.linspace(1,3,9)
md3=np.array([[mda],[mdb]])
print(md3)
#md3-->(2x9)

[[[3.   3.25 3.5  3.75 4.   4.25 4.5  4.75 5.  ]]

 [[1.   1.25 1.5  1.75 2.   2.25 2.5  2.75 3.  ]]]


In [41]:
np.size(md3)#Return the number of elements 

18

In [42]:
np.shape(md3)

(2, 1, 9)

In [45]:
np.ndim(md3)

3

In [44]:
np.alen(md1) #Return the length of the first dimension of the input array

2

#### converting 1d array to 2d array using reshape func:

In [65]:
m=np.arange(20)

In [66]:
m

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [67]:
np.ndim(m)

1

In [68]:
np.shape(m)

(20,)

In [69]:
m1=m.reshape(5,4)

In [74]:
m1

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19]])

In [75]:
dim1_to_dim2=np.linspace(1,5,10).reshape(5,2)
dim1_to_dim2

array([[1.        , 1.44444444],
       [1.88888889, 2.33333333],
       [2.77777778, 3.22222222],
       [3.66666667, 4.11111111],
       [4.55555556, 5.        ]])

In [76]:
np.size(dim1_to_dim2)

10

In [77]:
np.shape(dim1_to_dim2)

(5, 2)

#### converting 2D array back to 1D array using reshape func:

In [78]:
dim1_to_dim2

array([[1.        , 1.44444444],
       [1.88888889, 2.33333333],
       [2.77777778, 3.22222222],
       [3.66666667, 4.11111111],
       [4.55555556, 5.        ]])

In [79]:
dim2_to_dim1=dim1_to_dim2.reshape(10)

In [80]:
dim2_to_dim1

array([1.        , 1.44444444, 1.88888889, 2.33333333, 2.77777778,
       3.22222222, 3.66666667, 4.11111111, 4.55555556, 5.        ])

In [81]:
np.ndim(dim2_to_dim1)

1

In [95]:
dim1_to_dim2.reshape(10)

array([1.        , 1.44444444, 1.88888889, 2.33333333, 2.77777778,
       3.22222222, 3.66666667, 4.11111111, 4.55555556, 5.        ])

In [92]:
dim1_to_dim2

array([[1.        , 1.44444444],
       [1.88888889, 2.33333333],
       [2.77777778, 3.22222222],
       [3.66666667, 4.11111111],
       [4.55555556, 5.        ]])

In [93]:
np.shape(dim1_to_dim2)

(5, 2)

##### Note that .reshape() returns a new array with a different shape. The original array's shape remains unchanged.

#### The .reshape() method is not the only means of reorganizing data. Another means is the .ravel() method that will flatten a matrix to one dimension

In [90]:
m1

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19]])

In [87]:
m1.ravel()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

##### np.ravel will generate array representing a flattened 2-d array and it does not alter the shape of the source

In [88]:
m1

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19]])

# Selecting array elements

NumPy arrays can have their elements accessed via the [ ] operator.

In [75]:
a1

array([1, 2, 3, 4, 5, 6, 7])

In [76]:
a1[0]

1

In [77]:
a1[1]

2

In [78]:
a1[-1]

7

In [80]:
a2

array([1. , 2. , 3. , 4. , 5.5])

In [81]:
a1[3],a2[2]

(4, 3.0)

#### Elements in a two-dimensional array can be used by making use of two values separated by a comma, with the row first and column second

In [82]:
m1

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19]])

In [84]:
m1[1,2]

6

In [88]:
m1[3]

array([12, 13, 14, 15])

In [89]:
m1[2]

array([ 8,  9, 10, 11])

In [90]:
m1[:,2]

array([ 2,  6, 10, 14, 18])

# Logical operations on arrays

Logical operations can be applied to arrays to test the array values against specific
criteria.

In [91]:
log_oper=np.array([5,4,9,3,7,0,3])

In [92]:
log_oper

array([5, 4, 9, 3, 7, 0, 3])

In [95]:
log_oper<5

array([False,  True, False,  True, False,  True,  True])

In [96]:
log_oper>=2

array([ True,  True,  True,  True,  True, False,  True])

In [97]:
log_oper<2 or log_oper>5

ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()

In [99]:
(log_oper<2) | (log_oper>5)

array([False, False,  True, False,  True,  True, False])

In [101]:
(log_oper<2) & (log_oper>5)

array([False, False, False, False, False, False, False])

#### NumPy provides the np.vectorize() function, which applies an expression or function to an array in a vectorized manner.

In [103]:
def Opertions_on_Array (x):
    return x>5
np.vectorize(Opertions_on_Array)([1,2,3,9,8,7,])

array([False, False, False,  True,  True,  True])

#### Note that only the function is passed to np.vectorize(). The array is then passed as a parameter to the object that results from that operation.

In [116]:
def Opertions_on_Array (x):
    return x>5
np.vectorize(Opertions_on_Array)(log_oper)

array([False, False,  True, False,  True, False, False])

In [4]:
q1=np.linspace(1,3,10)
q2=np.arange(0,20,2)
def show_array ():
    return q1,q2
np.vectorize(show_array)()

(array([1.        , 1.22222222, 1.44444444, 1.66666667, 1.88888889,
        2.11111111, 2.33333333, 2.55555556, 2.77777778, 3.        ]),
 array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18]))

In [6]:
def CalulationOnArray (x,y):
    r1=x+y
    r2=x-y
    r3=x*y
    r4=x/2
    return r1,r2,r3,r4
np.vectorize(CalulationOnArray)(q1,q2)

(array([ 1.        ,  3.22222222,  5.44444444,  7.66666667,  9.88888889,
        12.11111111, 14.33333333, 16.55555556, 18.77777778, 21.        ]),
 array([  1.        ,  -0.77777778,  -2.55555556,  -4.33333333,
         -6.11111111,  -7.88888889,  -9.66666667, -11.44444444,
        -13.22222222, -15.        ]),
 array([ 0.        ,  2.44444444,  5.77777778, 10.        , 15.11111111,
        21.11111111, 28.        , 35.77777778, 44.44444444, 54.        ]),
 array([0.5       , 0.61111111, 0.72222222, 0.83333333, 0.94444444,
        1.05555556, 1.16666667, 1.27777778, 1.38888889, 1.5       ]))

#### A specific use of this type of an array of Boolean values is to select the elements from an array where the value in the Boolean array is True. This is referred to as Boolean selection and can be performed by passing the Boolean value array to the [ ] operator of the array from which the values are to be selected.

In [7]:
q2

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [11]:
r=q2<12
q2[r]

array([ 0,  2,  4,  6,  8, 10])

In [13]:
r.dtype

dtype('bool')

In [14]:
r

array([ True,  True,  True,  True,  True,  True, False, False, False,
       False])

In [15]:
np.sum(q2[r])

30

In [16]:
np.sum(q1)

20.0

#### Arrays can also be compared to other arrays:

In [17]:
q1

array([1.        , 1.22222222, 1.44444444, 1.66666667, 1.88888889,
       2.11111111, 2.33333333, 2.55555556, 2.77777778, 3.        ])

In [18]:
q2

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [21]:
q1<q2

array([False,  True,  True,  True,  True,  True,  True,  True,  True,
        True])

#### This also works across multi-dimensional arrays:

In [22]:
np.shape(q1)

(10,)

In [24]:
q3=q1.reshape(5,2)

In [25]:
q3

array([[1.        , 1.22222222],
       [1.44444444, 1.66666667],
       [1.88888889, 2.11111111],
       [2.33333333, 2.55555556],
       [2.77777778, 3.        ]])

In [29]:
q4=q2.reshape(5,2)

In [30]:
q4

array([[ 0,  2],
       [ 4,  6],
       [ 8, 10],
       [12, 14],
       [16, 18]])

In [31]:
q3>q4

array([[ True, False],
       [False, False],
       [False, False],
       [False, False],
       [False, False]])

In [32]:
q3[2,1]

2.111111111111111

In [33]:
q3[2,1]=11.5

In [34]:
q3>q4

array([[ True, False],
       [False, False],
       [False,  True],
       [False, False],
       [False, False]])

# Slicing arrays

In [36]:
q1

array([ 1.        ,  1.22222222,  1.44444444,  1.66666667,  1.88888889,
       11.5       ,  2.33333333,  2.55555556,  2.77777778,  3.        ])

In [39]:
q1[2:8]

array([ 1.44444444,  1.66666667,  1.88888889, 11.5       ,  2.33333333,
        2.55555556])

In [40]:
np.round(q1[2:8],2)

array([ 1.44,  1.67,  1.89, 11.5 ,  2.33,  2.56])

In [41]:
q1[2:8:2]#method-1

array([1.44444444, 1.88888889, 2.33333333])

In [42]:
q1[::2]#method-2

array([1.        , 1.44444444, 1.88888889, 2.33333333, 2.77777778])

#### Slicing of 2D arrays

In [43]:
q4

array([[ 0,  2],
       [ 4,  6],
       [ 8, 10],
       [12, 14],
       [16, 18]])

In [45]:
q4[:,1]

array([ 2,  6, 10, 14, 18])

In [50]:
q4[2:3]

array([[ 8, 10]])

In [51]:
q4[1:4]

array([[ 4,  6],
       [ 8, 10],
       [12, 14]])

In [52]:
q4[1:4:2]

array([[ 4,  6],
       [12, 14]])

## In linear algebra, it is common to transpose a matrix. This can be performed with the np.transpose()

In [104]:
t1=np.linspace(1,5,12).reshape(4,3).round(2)

In [105]:
t1

array([[1.  , 1.36, 1.73],
       [2.09, 2.45, 2.82],
       [3.18, 3.55, 3.91],
       [4.27, 4.64, 5.  ]])

In [107]:
np.shape(t1)

(4, 3)

In [109]:
t2=t1.transpose()#method-1

In [110]:
t2

array([[1.  , 2.09, 3.18, 4.27],
       [1.36, 2.45, 3.55, 4.64],
       [1.73, 2.82, 3.91, 5.  ]])

In [111]:
np.shape(t2)

(3, 4)

In [113]:
t2.T#method-2

array([[1.  , 1.36, 1.73],
       [2.09, 2.45, 2.82],
       [3.18, 3.55, 3.91],
       [4.27, 4.64, 5.  ]])

# Combining arrays

#### Arrays can be combined in various ways. This process in NumPy is referred to as stacking. Stacking can take various forms, including horizontal, vertical, and depth-wise stacking.

In [9]:
a=np.arange(0,30,2).reshape(3,5)

In [10]:
a

array([[ 0,  2,  4,  6,  8],
       [10, 12, 14, 16, 18],
       [20, 22, 24, 26, 28]])

In [12]:
b=(a+2)*10

In [13]:
b

array([[ 20,  40,  60,  80, 100],
       [120, 140, 160, 180, 200],
       [220, 240, 260, 280, 300]])

#### Horizontal stacking combines two arrays in a manner where the columns of the second array are placed to the right of those in the first array.

In [14]:
np.hstack((a,b))

array([[  0,   2,   4,   6,   8,  20,  40,  60,  80, 100],
       [ 10,  12,  14,  16,  18, 120, 140, 160, 180, 200],
       [ 20,  22,  24,  26,  28, 220, 240, 260, 280, 300]])

#### This functionally is equivalent to using the np.concatenate() function

In [16]:
np.concatenate((a,b),axis=1)

array([[  0,   2,   4,   6,   8,  20,  40,  60,  80, 100],
       [ 10,  12,  14,  16,  18, 120, 140, 160, 180, 200],
       [ 20,  22,  24,  26,  28, 220, 240, 260, 280, 300]])

#### Vertical stacking returns a new array with the contents of the second array as appended rows of the first array

In [17]:
np.vstack((a,b))

array([[  0,   2,   4,   6,   8],
       [ 10,  12,  14,  16,  18],
       [ 20,  22,  24,  26,  28],
       [ 20,  40,  60,  80, 100],
       [120, 140, 160, 180, 200],
       [220, 240, 260, 280, 300]])

In [19]:
np.concatenate((a,b),axis=0)

array([[  0,   2,   4,   6,   8],
       [ 10,  12,  14,  16,  18],
       [ 20,  22,  24,  26,  28],
       [ 20,  40,  60,  80, 100],
       [120, 140, 160, 180, 200],
       [220, 240, 260, 280, 300]])

#### Depth stacking takes a list of arrays and arranges them in order along an additional axis referred to as the depth

In [20]:
np.dstack((a,b))

array([[[  0,  20],
        [  2,  40],
        [  4,  60],
        [  6,  80],
        [  8, 100]],

       [[ 10, 120],
        [ 12, 140],
        [ 14, 160],
        [ 16, 180],
        [ 18, 200]],

       [[ 20, 220],
        [ 22, 240],
        [ 24, 260],
        [ 26, 280],
        [ 28, 300]]])

#### Horizontal and Vertical stacking of 1D array using np.column_stack() and np.row_stack()

In [23]:
one_D_array=np.linspace(4,6,8).round(2)

In [24]:
one_D_array

array([4.  , 4.29, 4.57, 4.86, 5.14, 5.43, 5.71, 6.  ])

In [25]:
one_D_2nd_array=(one_D_array+10)*10

In [26]:
one_D_2nd_array

array([140. , 142.9, 145.7, 148.6, 151.4, 154.3, 157.1, 160. ])

In [27]:
np.hstack((one_D_array,one_D_2nd_array))

array([  4.  ,   4.29,   4.57,   4.86,   5.14,   5.43,   5.71,   6.  ,
       140.  , 142.9 , 145.7 , 148.6 , 151.4 , 154.3 , 157.1 , 160.  ])

# Splitting arrays

#### Arrays can also be split into multiple arrays along the horizontal, vertical, and depth axes using the np.hsplit(), np.vsplit(), and np.dsplit() functions.

In [4]:
split_array=np.arange(0,20).reshape(5,4)
split_array

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19]])

In [6]:
np.hsplit(split_array,4) #column wise

[array([[ 0],
        [ 4],
        [ 8],
        [12],
        [16]]), array([[ 1],
        [ 5],
        [ 9],
        [13],
        [17]]), array([[ 2],
        [ 6],
        [10],
        [14],
        [18]]), array([[ 3],
        [ 7],
        [11],
        [15],
        [19]])]

In [12]:
np.hsplit(split_array,2) #column wise

[array([[ 0,  1],
        [ 4,  5],
        [ 8,  9],
        [12, 13],
        [16, 17]]), array([[ 2,  3],
        [ 6,  7],
        [10, 11],
        [14, 15],
        [18, 19]])]

In [13]:
np.hsplit(split_array,3) #column wise

ValueError: array split does not result in an equal division

##### Also, the following code splits an array along specific columns

In [16]:
split_array

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19]])

In [24]:
np.hsplit(split_array,[1,3])

[array([[ 0],
        [ 4],
        [ 8],
        [12],
        [16]]), array([[ 1,  2],
        [ 5,  6],
        [ 9, 10],
        [13, 14],
        [17, 18]]), array([[ 3],
        [ 7],
        [11],
        [15],
        [19]])]

#### np.vsplit(),np.dsplit() and np.split()

# Useful numerical methods of NumPy arrays

In [48]:
Array=np.random.randint(12,30,25).reshape(5,5)

In [49]:
Array

array([[29, 20, 13, 27, 15],
       [20, 29, 26, 15, 21],
       [13, 18, 17, 29, 17],
       [15, 15, 23, 22, 18],
       [24, 22, 27, 27, 12]])

In [50]:
print(f"the min value is {np.min(Array)}")

the min value is 12


In [51]:
print(f"the mix value is {np.max(Array)}")

the mix value is 29


In [56]:
print(f"the position of min value is {np.argmin(Array)}th")

the position of min value is 24th


In [57]:
print(f"the position of max value is {np.argmax(Array)}th")

the position of max value is 0th


In [59]:
print(f"the min values of each column is {np.min(Array,axis=0)}")

the min values of each column is [13 15 13 15 12]


In [60]:
print(f"the max values of each column is {np.max(Array,axis=0)}")

the max values of each column is [29 29 27 29 21]


In [75]:
print(f"the min values of each row is {np.min(Array,axis=1)}")

the min values of each row is [13 15 13 15 12]


In [62]:
print(f"the max values of each row is {np.max(Array,axis=1)}")

the max values of each row is [29 29 29 23 27]


#### The .mean(), .std(), and .var() methods compute the mathematical mean, standard deviation, and variance of the values in an array

In [85]:
print(f"the mean is {np.mean(Array)}")

the mean is 20.56


In [87]:
print(f"the standard deviation is {np.std(Array).round(3)}")

the standard deviation is 5.441


In [89]:
print(f"the variance is {np.var(Array).round(3)}")

the variance is 29.606


#### The sum and products of all the elements in an array can be computed with the .sum() and .prod() methods

In [91]:
print(f"the sum is {np.sum(Array)}")

the sum is 514


In [92]:
print(f"the product is {np.prod(Array)}")

the product is 1863204864


#### The cumulative sum and products can be computed with the .cumsum() and .cumprod() methods:

In [93]:
np.cumsum(Array)

array([ 29,  49,  62,  89, 104, 124, 153, 179, 194, 215, 228, 246, 263,
       292, 309, 324, 339, 362, 384, 402, 426, 448, 475, 502, 514],
      dtype=int32)

In [94]:
np.cumprod(Array)

array([         29,         580,        7540,      203580,     3053700,
          61074000,  1771146000, -1194844256,  -742794656,  1581181408,
        -919478176,   629262016,  2107519680,   988528576,  -374883392,
       -1328283584,  1550582720,  1303664192, -1384158848,   854944512,
        -956168192,   439136256, -1028222976, -1992216576,  1863204864],
      dtype=int32)

#### The .all() method returns True if all elements of an array are true, and .any() returns True if any element of the array is true

In [96]:
np.all(Array>30)

False

In [97]:
np.all(Array<30)

True

In [98]:
np.all(Array==12)

False

In [99]:
np.any(Array==12)

True

In [111]:
Array1=np.random.randn(150).reshape(30,5).round(2)
print("the give matrix is:"'\n''\n',Array1,'\n''\n')
print(f"the min value is {np.min(Array1)}"'\n')
print(f"the mix value is {np.max(Array1)}"'\n')
print(f"the position of min value is {np.argmin(Array1)}th"'\n')
print(f"the position of max value is {np.argmax(Array1)}th"'\n')
print(f"the min values of each column is {np.min(Array1,axis=0)}"'\n')
print(f"the max values of each column is {np.max(Array1,axis=0)}"'\n')
print(f"the min values of each row is {np.min(Array1,axis=1)}"'\n')
print(f"the max values of each row is {np.max(Array1,axis=1)}"'\n')

the give matrix is:

 [[ 0.76  1.33 -1.22  0.59 -0.25]
 [-0.74 -0.49  0.25 -0.44 -0.09]
 [-0.71  1.13  0.32 -0.93 -0.41]
 [ 0.59  1.22  0.31  1.6  -2.59]
 [-0.18 -0.02 -0.14  0.65  0.54]
 [ 1.48 -0.07  2.41 -0.3  -1.04]
 [-0.12 -0.63 -0.44 -0.57 -1.21]
 [ 0.39  0.23  1.31 -2.7  -0.85]
 [-1.15  1.09  0.69 -0.56  0.24]
 [-0.4   0.35  0.85 -0.27  2.3 ]
 [ 0.04 -0.58  0.   -0.34  0.46]
 [ 1.16 -0.53  1.03  2.28  0.29]
 [ 0.72  1.11  0.72 -1.96  0.2 ]
 [-1.51 -1.69 -0.89  1.06 -0.82]
 [-0.98 -0.44  1.25  1.53  0.38]
 [-1.41  0.11  1.01 -0.01 -1.21]
 [ 1.49  0.84 -0.73 -0.31 -0.19]
 [ 0.4  -0.45  0.24 -0.17 -1.02]
 [ 1.03 -1.27 -0.21 -0.92 -0.45]
 [-0.69  0.33 -0.27  0.1  -0.39]
 [ 0.46  0.85  0.43  1.93 -1.63]
 [-0.09  0.77  0.39 -0.5   0.53]
 [-0.18 -0.5  -0.04  0.18  1.8 ]
 [-0.41 -0.37  0.75 -0.28 -1.53]
 [ 1.26  1.2   0.27  1.52 -0.62]
 [-1.33  0.41 -0.32  0.81 -1.75]
 [ 0.47  0.09  0.91  2.06 -0.29]
 [ 0.06 -0.05  1.39  0.57  1.01]
 [ 0.63  0.51 -0.68  0.74 -0.9 ]
 [-1.15  0.84 -1.45 -

In [112]:
Array1=np.linspace(1,2).reshape(10,5).round(2)
print("the give matrix is:"'\n''\n',Array1,'\n''\n')
print(f" the min value is {np.min(Array1)}"'\n',f"the mix value is {np.max(Array1)}"'\n',f"the position of min value is {np.argmin(Array1)}th"'\n',f"the position of max value is {np.argmax(Array1)}th"'\n',f"the min values of each column is {np.min(Array1,axis=0)}"'\n',f"the max values of each column is {np.max(Array1,axis=0)}"'\n',f"the min values of each row is {np.min(Array1,axis=1)}"'\n',f"the max values of each row is {np.max(Array1,axis=1)}"'\n')

the give matrix is:

 [[1.   1.02 1.04 1.06 1.08]
 [1.1  1.12 1.14 1.16 1.18]
 [1.2  1.22 1.24 1.27 1.29]
 [1.31 1.33 1.35 1.37 1.39]
 [1.41 1.43 1.45 1.47 1.49]
 [1.51 1.53 1.55 1.57 1.59]
 [1.61 1.63 1.65 1.67 1.69]
 [1.71 1.73 1.76 1.78 1.8 ]
 [1.82 1.84 1.86 1.88 1.9 ]
 [1.92 1.94 1.96 1.98 2.  ]] 


 the min value is 1.0
 the mix value is 2.0
 the position of min value is 0th
 the position of max value is 49th
 the min values of each column is [1.   1.02 1.04 1.06 1.08]
 the max values of each column is [1.92 1.94 1.96 1.98 2.  ]
 the min values of each row is [1.   1.1  1.2  1.31 1.41 1.51 1.61 1.71 1.82 1.92]
 the max values of each row is [1.08 1.18 1.29 1.39 1.49 1.59 1.69 1.8  1.9  2.  ]

